OpenSourcePolitics/dbt-processing

- projects/cour_des_comptes/models/intermediate/decidim_awesome/int_decidim_awesome_private_proposal_fields.sql
- projects/cour_des_comptes/models/intermediate/decidim_awesome/schema.yml
- projects/cour_des_comptes/models/intermediate/users/schema.yml
- projects/cour_des_comptes/models/staging/decidim/schema.yml
- projects/cour_des_comptes/models/staging/decidim/stg_decidim_awesome_private_proposal_fields.sql
In this PR, we : 
- create a model for decidim_awesome_private_proposal_fields
- add tests
> feat(cdc): create decidim_awesome_private_proposal_fields models

- projects/angers/dbt_project.yml
- projects/cese/dbt_project.yml
- projects/cour_des_comptes/dbt_project.yml
- projects/demo/dbt_project.yml
- projects/grand_nancy/dbt_project.yml
- projects/lyon/dbt_project.yml
- projects/marseille/dbt_project.yml
- projects/sytral/dbt_project.yml
- projects/thionville/dbt_project.yml
- projects/toulouse/dbt_project.yml
- projects/tours/dbt_project.yml
- projects/valbonne/dbt_project.yml
In this PR, we switch to table materialization for the marts and intermediate models in order to server faster the query in Metabase.
> feat(projects): add materialization table

- .gitignore
- projects/lyon/models/intermediate/matomo/int_matomo_downloads.sql
- projects/lyon/models/intermediate/matomo/schema.yml
- projects/lyon/models/staging/matomo/schema.yml
- projects/lyon/models/staging/matomo/stg_matomo_downloads.sql
added : 
- staging model
- schema.yml in staging (to be completed)
- intermediate model 
- schema.yml in intermediate (to be completed)
> adding staging and intermediate models with test

- projects/meyzieu/dbt_project.yml
- projects/meyzieu/models/staging/matomo/stg_matomo_referrers.sql
added : 
- stg_matomo_referrers with manually created sub column
> adding specific stg matomo referrers model

- projects/demo/models/marts/exposures_matomo_page_views.yml
- projects/demo/models/marts/exposures_matomo_page_views_evolution.yml
- projects/demo/models/marts/exposures_matomo_pagees_bounce_rate.yml
- projects/demo/models/marts/exposures_matomo_pages_bounce_rate.yml
- projects/demo/models/marts/meetings/exposures_meetings.yml
- projects/demo/models/marts/meetings/exposures_meetings_by_users.yml
- projects/demo/models/marts/meetings/exposures_meetings_type.yml
- projects/demo/models/marts/proposals/exposures_proposals.yml
- projects/demo/models/marts/proposals/exposures_proposals_categories.yml
- projects/demo/models/marts/proposals/exposures_proposals_evolution.yml
- projects/demo/models/marts/proposals/exposures_proposals_scopes.yml
added : yml exposures files in users, proposals, and meetings folders
> adding local dashboard exposures yml files

- .github/workflows/colombes_models_run.yml
- .github/workflows/colombes_models_run_preproduction.yml
- projects/colombes/.gitignore
- projects/colombes/README.md
- projects/colombes/config.yml
- projects/colombes/dbt_project.yml
- projects/colombes/packages.yml
- projects/colombes/profiles.yml
- projects/colombes/requirements.txt
added : all dbt project files for Colombes
> feat(colombes) : adding Colombes dbt project

- projects/packages/initiatives/models/marts/initiatives_comments.sql
> feat(initiatives): add specific model to retrieve comments (WIP)

- .github/workflows/nanterre_models_run_preproduction.yml
- .github/workflows/nanterre_models_run_production.yml
- projects/nanterre/.gitignore
- projects/nanterre/README.md
- projects/nanterre/config.yml
- projects/nanterre/dbt_project.yml
- projects/nanterre/packages.yml
- projects/nanterre/profiles.yml
- projects/nanterre/requirements.txt
adding Nanterre dbt project + GA worklow files
> feat(nanterre) : adding Nanterre dbt project

- .github/workflows/mel_models_run_preproduction.yml
- .github/workflows/mel_models_run_production.yml
- projects/mel/.gitignore
- projects/mel/README.md
- projects/mel/config.yml
- projects/mel/dbt_project.yml
- projects/mel/packages.yml
- projects/mel/profiles.yml
- projects/mel/requirements.txt
adding MEL dbt project + GA workflow files
> feat(mel) : adding MEL dbt project

- .github/workflows/malakoff_models_run_preproduction.yml
- .github/workflows/malakoff_models_run_production.yml
- projects/malakoff/.gitignore
- projects/malakoff/README.md
- projects/malakoff/config.yml
- projects/malakoff/dbt_project.yml
- projects/malakoff/packages.yml
- projects/malakoff/profiles.yml
- projects/malakoff/requirements.txt
adding malakoff dbt project and GA workflow files
> feat(malakoff): adding malakoff dbt project

- .github/workflows/chambery_models_run_preproduction.yml
- .github/workflows/chambery_models_run_production.yml
- projects/chambery/.gitignore
- projects/chambery/README.md
- projects/chambery/config.yml
- projects/chambery/dbt_project.yml
- projects/chambery/packages.yml
- projects/chambery/profiles.yml
added : chambery dbt projet + GA workflow files
> feat(chambery) : adding chambery dbt project

- .github/workflows/bagneux_models_run.yml
- .github/workflows/bagneux_models_run_preproduction.yml
- .github/workflows/bagneux_models_run_production.yml
- projects/bagneux/.gitignore
- projects/bagneux/README.md
- projects/bagneux/config.yml
- projects/bagneux/dbt_project.yml
- projects/bagneux/packages.yml
- projects/bagneux/profiles.yml
- projects/bagneux/requirements.txt
Adding Bagneux dbt project and necessary files
> Add bagneux

- projects/demo/models/intermediate/users/int_users.sql
- projects/demo/models/marts/users/all_users.sql
- projects/demo/models/marts/users/schema.yml
- projects/demo/models/staging/decidim/stg_decidim_users.sql
added : 3 new columns 
- spam
- spam_probability
- spam_reported_at
- data test in marts to check spam probability
> feat(add) : adding spam report colums

- projects/grand_nancy/dbt_project.yml
> feat(test) : disabling demo categories tests for Grand Nancy

- projects/demo/models/intermediate/users/schema.yml
- projects/demo/models/staging/decidim/schema.yml
added : data and unit test for spam detection
> Add test and fix

- .github/workflows/cachan_models_run_preproduction.yml
- .github/workflows/cachan_models_run_production.yml
- projects/cachan/.gitignore
- projects/cachan/README.md
- projects/cachan/config.yml
- projects/cachan/dbt_project.yml
- projects/cachan/packages.yml
- projects/cachan/profiles.yml
- projects/cachan/requirements.txt
added : 
- Cachan dbt project
- GA worflow files
> feat(cachan) : adding Cachan dbt project

- .github/workflows/nets4dem_models_run_preproduction.yml
- .github/workflows/nets4dem_models_run_production.yml
- projects/nets4dem/.gitignore
- projects/nets4dem/README.md
- projects/nets4dem/config.yml
- projects/nets4dem/dbt_project.yml
- projects/nets4dem/packages.yml
- projects/nets4dem/profiles.yml
- projects/nets4dem/requirements.txt
added : 
- Nets4dem dbt project
- GA workflow files
> feat(net4dem) : adding Nets4dem dbt project

- projects/demo/models/intermediate/proposals/int_proposals.sql
> fix(demo): add proposal states French translations

- projects/demo/models/staging/decidim/blogs_posts/stg_decidim_blogs_posts.sql
- projects/demo/models/staging/decidim/forms/stg_decidim_forms_questions.sql
- projects/demo/models/staging/decidim/proposals/stg_decidim_proposals.sql
- projects/demo/models/staging/decidim/stg_decidim_attachments.sql
- projects/demo/models/staging/decidim/stg_decidim_comments.sql
- projects/demo/models/staging/decidim/stg_decidim_meetings.sql
+ slight refacto of staging models
> feat(demo): anticipate new columns for 0.29 migration

- projects/demo/models/staging/matomo/schema.yml
- projects/demo/models/staging/matomo/stg_matomo_campaign_mediums.sql
- projects/demo/models/staging/matomo/stg_matomo_campaign_names.sql
- projects/demo/models/staging/matomo/stg_matomo_campaign_source_medium.sql
- projects/demo/models/staging/matomo/stg_matomo_campaign_sources.sql
added models : 
- stg_matomo_campaign_mediums
- stg_matomo_campaign_names
- stg_matomo_campaign_source_medium
- stg_matomo_campaign_sources
+ tables added to schema.yml in sources
> feat(campaigns) : adding matomo campaigns models

- projects/marseille/models/marts/participations_with_impersonation_info.sql
based on pre-existing proposals with impersonation info model
> feat(marseille): add participations with impersonation info model

- projects/demo/models/intermediate/forms/answers_matrix.sql
- projects/demo/models/intermediate/forms/answers_short_and_long_answer.sql
- projects/demo/models/intermediate/forms/schema.yml
Needed for https://metabase.osp.cat/question/16735-25-nombre-de-followers-approximatif
> fix: retrieve custom body for answers to matrix questions
